<?php
session_start();
require_once('../config.php');

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'inventory') {
    header("Location: ../login/login.php");
    exit();
}

// Fetch all inventory items
$query = "SELECT * FROM inventory ORDER BY item_name ASC";
$result = $con->query($query);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inventory Report | Little Haven</title>
    
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&display=swap" rel="stylesheet">
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    
    <!-- html2pdf.js CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
    
    <style>
        :root {
            --primary: #FF9F1C;
            --secondary: #264653;
            --text-main: #1A202C;
            --text-muted: #718096;
        }

        body {
            font-family: 'Outfit', sans-serif;
            background-color: #f7fafc;
            color: var(--text-main);
            padding: 40px;
        }

        .container {
            max-width: 1000px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            border-radius: 20px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.05);
        }

        .report-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 40px;
            border-bottom: 2px solid #edf2f7;
            padding-bottom: 20px;
        }

        .logo-area h2 {
            color: var(--secondary);
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .report-info {
            text-align: right;
        }

        .report-info p {
            color: var(--text-muted);
            font-size: 0.9rem;
        }

        .controls {
            margin-bottom: 30px;
            display: flex;
            gap: 15px;
            justify-content: flex-end;
        }

        .btn {
            padding: 12px 25px;
            border-radius: 10px;
            font-weight: 600;
            text-decoration: none;
            display: flex;
            align-items: center;
            gap: 10px;
            cursor: pointer;
            transition: all 0.3s;
            border: none;
        }

        .btn-back { background: #E2E8F0; color: var(--text-main); }
        .btn-download { background: var(--secondary); color: white; }
        .btn:hover { transform: translateY(-2px); opacity: 0.9; }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th {
            background: #f8fafc;
            padding: 15px;
            text-align: left;
            font-size: 0.85rem;
            color: var(--text-muted);
            border-bottom: 2px solid #edf2f7;
        }

        td {
            padding: 15px;
            border-bottom: 1px solid #edf2f7;
            font-size: 0.95rem;
        }

        .badge {
            padding: 4px 8px;
            border-radius: 12px;
            font-size: 0.75rem;
            font-weight: 700;
        }

        .badge-low { background: #FFF5F5; color: #E53E3E; }
        .badge-ok { background: #F0FFF4; color: #38A169; }

        @media print {
            .controls { display: none; }
            body { padding: 0; background: white; }
            .container { box-shadow: none; max-width: 100%; }
        }
    </style>
</head>
<body>

    <div class="controls no-print">
        <a href="inventory_dashboard.php" class="btn btn-back"><i class="fas fa-arrow-left"></i> Back to Dashboard</a>
        <button onclick="downloadPDF()" class="btn btn-download"><i class="fas fa-file-pdf"></i> Download PDF</button>
    </div>

    <div class="container" id="reportContent">
        <div class="report-header">
            <div class="logo-area">
                <h2><i class="fas fa-hands-holding-child"></i> Little Haven Daycare</h2>
                <p>Inventory Stock Report</p>
            </div>
            <div class="report-info">
                <p>Date Generated: <strong><?php echo date('d M Y'); ?></strong></p>
                <p>Generated by: <strong><?php echo $_SESSION['fullname']; ?></strong></p>
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Category</th>
                    <th>Current Stock</th>
                    <th>Unit</th>
                    <th>Threshold</th>
                    <th>Supplier</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <?php while ($item = $result->fetch_assoc()): ?>
                    <?php 
                        $isLow = $item['quantity'] <= $item['reorder_threshold'];
                        $isOutOfStock = $item['quantity'] <= 0;
                    ?>
                    <tr>
                        <td><strong><?php echo $item['item_name']; ?></strong></td>
                        <td><?php echo $item['category']; ?></td>
                        <td><?php echo $item['quantity']; ?></td>
                        <td><?php echo $item['unit']; ?></td>
                        <td><?php echo $item['reorder_threshold']; ?></td>
                        <td><?php echo $item['supplier_name'] ?: '-'; ?></td>
                        <td>
                            <?php if ($isOutOfStock): ?>
                                <span class="badge badge-low">Out of Stock</span>
                            <?php elseif ($isLow): ?>
                                <span class="badge badge-low">Low Stock</span>
                            <?php else: ?>
                                <span class="badge badge-ok">Normal</span>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endwhile; ?>
            </tbody>
        </table>

        <div style="margin-top: 50px; text-align: center; color: var(--text-muted); font-size: 0.8rem;">
            <p>© <?php echo date('Y'); ?> Little Haven Daycare Management System. All rights reserved.</p>
        </div>
    </div>

    <script>
        function downloadPDF() {
            const element = document.getElementById('reportContent');
            const opt = {
                margin:       10,
                filename:     'Little_Haven_Inventory_Report_<?php echo date('Y-m-d'); ?>.pdf',
                image:        { type: 'jpeg', quality: 0.98 },
                html2canvas:  { scale: 2 },
                jsPDF:        { unit: 'mm', format: 'a4', orientation: 'landscape' }
            };

            // New Promise-based usage:
            html2pdf().set(opt).from(element).save();
        }
    </script>
</body>
</html>
